# Generated by Django 5.1 on 2024-09-16 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "token",
                    models.CharField(editable=False, max_length=255, unique=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("last_used", models.DateTimeField(editable=False, null=True)),
                ("read_only_access", models.BooleanField(default=False)),
                ("full_access", models.BooleanField(default=False)),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "API Token",
                "verbose_name_plural": "API Tokens",
                "db_table": "headless_api_token",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
    ]
