# Generated by Django 5.1 on 2024-09-16 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("headless_api_token", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="edited_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_edited",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Edited by",
            ),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="auth.permission"
            ),
        ),
    ]
