# Generated by Django 5.1 on 2024-09-16 07:44

import headless.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("headless_api_token", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="token",
            field=models.CharField(
                default=headless.utils.generate_password,
                editable=False,
                max_length=255,
                unique=True,
            ),
        ),
    ]
