# Generated by Django 5.1 on 2024-09-16 10:51

import django.db.models.deletion
import headless.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("headless_api_token", "0003_alter_apitoken_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="full_access",
            field=models.BooleanField(default=False, verbose_name="Full access"),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="is_enabled",
            field=models.BooleanField(default=True, verbose_name="Enabled"),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="last_used",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="Last used"
            ),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="auth.permission",
                verbose_name="Permissions",
            ),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="read_only_access",
            field=models.BooleanField(default=False, verbose_name="Read-only"),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="token",
            field=models.CharField(
                default=headless.utils.generate_password,
                editable=False,
                max_length=255,
                unique=True,
                verbose_name="Token",
            ),
        ),
        migrations.CreateModel(
            name="ApiTokenUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                ("method", models.CharField(max_length=10, verbose_name="Method")),
                ("path", models.CharField(max_length=255, verbose_name="Path")),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="headless_api_token.apitoken",
                        verbose_name="Token",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Token Usage",
                "verbose_name_plural": "API Token Usages",
                "db_table": "headless_api_token_usage",
                "ordering": ["timestamp"],
            },
        ),
    ]
