# Generated by Django 5.1 on 2024-09-16 06:37

import headless.fields
import headless.media_library.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=headless.media_library.models.generate_uuid,
                        verbose_name="Bestand",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Beschrijft een afbeelding voor SEO en schermlezers.",
                        max_length=255,
                        verbose_name="Alt-tekst",
                    ),
                ),
                (
                    "tags",
                    headless.fields.TagField(
                        blank=True, default=list, verbose_name="Tags"
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(
                        editable=False, null=True, verbose_name="File size"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("image", "Afbeelding"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("file", "Bestand"),
                        ],
                        default="file",
                        max_length=20,
                        verbose_name="Bestandstype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media",
                "verbose_name_plural": "Media",
                "db_table": "headless_media",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
    ]
