# Generated by Django 5.1.2 on 2024-10-11 10:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("headless_media_library", "0003_folder_media_folder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "template",
                    models.CharField(
                        choices=[("1.44", "Profielafbeelding"), ("1.75", "Kaart")],
                        verbose_name="Template",
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_edited",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Edited by",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="headless_media_library.media",
                        verbose_name="Media item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crop",
                "verbose_name_plural": "Crops",
                "db_table": "headless_crop",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
                "unique_together": {("template", "media")},
            },
        ),
    ]
