# Generated by Django 5.1.2 on 2024-10-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("headless_media_library", "0004_crop"),
    ]

    operations = []
