# Generated by Django 5.1.3 on 2024-11-11 08:47

import headless.media_library.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("headless_media_library", "0005_alter_crop_selection_alter_crop_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="crop",
            field=headless.media_library.models.CropField(
                blank=True, default=list, verbose_name="Crop"
            ),
        ),
        migrations.DeleteModel(
            name="Crop",
        ),
    ]
